#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"


# Make sure system preferences is always on top.
#yabai -m rule --add app="^System Preferences$" manage=off
#yabai -m rule --add app="System Preferences" manage=off
#yabai -m rule --add app="Mail" manage=off
#yabai -m rule --add app="iTerm2" manage=off
#yabai -m rule --add app="Safari" manage=off
#yabai -m rule --add app="Music" manage=off
#yabai -m rule --add app="zoom.us" manage=off 
#yabai -m rule --add app="zoom.us" sticky=on
#yabai -m rule --add app="VirtualBoxWM" manage=off
#yabai -m rule --add app="VirtualBox" manage=off
#yabai -m rule --add app="qutebrowser" manage=on
#yabai -m rule --add app="mpv" manage=on
#yabai -m app="Alacritty" --padding abs:20:20:20:20
#yabai -m rule --add app="iTerm2" opacity=0.5
#yabai -m rule --add app="zoom.us" opacity=0.5

# Disable window shadow
yabai -m config window_shadow off

# bar settings
#yabai -m config status_bar                   on 
#yabai -m config status_bar_position          top
#yabai -m config status_bar_text_font         "SF Mono:Bold:22.0"
#yabai -m config status_bar_icon_font         "SF Mono:Medium:22.0"
#yabai -m config status_bar_background_color  0xff000000
#yabai -m config status_bar_foreground_color  0xffffffff
#yabai -m config status_bar_space_icon_strip  ?? ?? ?? ?? ?? ?? ??
#yabai -m config status_bar_power_icon_strip  ??
#yabai -m config status_bar_space_icon        ??
#yabai -m config status_bar_clock_icon        ??

# global settings
#yabai -m config window_topmost on
yabai -m config focus_follows_mouse          autofocus
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
yabai -m config split_ratio                  0.50
#yabai -m config window_opacity               off
#yabai -m config window_opacity_duration      0.5
yabai -m config window_shadow                off
yabai -m config window_border                on
#yabai -m config window_border_placement      inset
yabai -m config window_border_width          1
yabai -m config window_border_radius         0.8
yabai -m config active_window_border_topmost on
yabai -m config active_window_border_color   0xFFFFFFFF
#Hex(9CE34E)  0xFF9CE34E 
#FF12F359 > Hex(12F359)
yabai -m config normal_window_border_color   0xff505050
#yabai -m config insert_window_border_color   0xffd75f5f
#yabai -m config active_window_opacity        1.0
#yabai -m config normal_window_opacity        0.7
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       float
#yabai -m config top_padding                  76
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   20

# Override default layout for space 1 only
yabai -m config --space 1 layout bsp
yabai -m config --space 2 layout bsp
yabai -m config --space 3 layout bsp
#yabai -m config --app="Alacritty" --padding abs:20:20:20:20
#yabai -m config --app="Mail" --toggle float
#yabai -m config --app="System Preferences" --toggle float

# Floating point value between 0 and 1 (default: 0.5)
#yabai -m config split_ratio 0.6

# sourcing config file for limelight
#. ~/.config/limelight/limelightrc

# kill any existing limelight process if one exists, before we launch a new one
#killall limelight &> /dev/null
#limelight -c ~/.config/limelight/limelightrc &> /dev/null &
sudo yabai --load-sa yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
echo "yabai configuration loaded.."



yabai -m rule --add title='mylauncher' manage=off sticky=on layer=above border=off
yabai -m rule --add title="Pixelmator Pro" manage=off window_topmost=off
yabai -m rule --add app="zoom.us" manage=off layer=above
yabai -m rule --add app="Raycast" manage=off layer=above
yabai -m rule --add title="^Visual Studio Code$" manage=off #window_topmost=off
yabai -m rule --add app="DatapGrip" manage=off #window_topmost=off
yabai -m rule --add app="Notes" manage=off window_topmost=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Google Chrome$" manage=on
#yabai -m config --app="^Google Chrome$" --padding abs:20:20:20:20


# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on

# which display a windhow should become managed at when created
yabai -m config window_origin_display        default
# auto tile windows to the side
yabai -m config window_placement             second_child

# make floating windows stay on top
#yabai -m config window_topmost               on
